"""
Monitor — Prometheus metrics export.

Exposes a /metrics HTTP endpoint on port cfg.metrics_port (default 9090).
All metrics are prefixed with `polymarket_hft_`.
"""
from __future__ import annotations

import asyncio
import logging
import time
from typing import Optional

try:
    from prometheus_client import (
        Counter, Gauge, Histogram, Summary,
        start_http_server, REGISTRY,
    )
    _PROMETHEUS_AVAILABLE = True
except ImportError:
    _PROMETHEUS_AVAILABLE = False

from core.config import cfg

log = logging.getLogger(__name__)

# ── Counters ──────────────────────────────────────────────────────────────────
if _PROMETHEUS_AVAILABLE:
    orders_submitted = Counter(
        "polymarket_hft_orders_submitted_total",
        "Total orders submitted to CLOB",
        ["source", "side"],
    )
    orders_rejected = Counter(
        "polymarket_hft_orders_rejected_total",
        "Total orders rejected by risk engine",
        ["reason"],
    )
    orders_filled = Counter(
        "polymarket_hft_orders_filled_total",
        "Total orders confirmed filled",
    )
    signals_generated = Counter(
        "polymarket_hft_signals_generated_total",
        "Total signals generated by signal worker",
        ["channel"],
    )
    api_calls = Counter(
        "polymarket_hft_api_calls_total",
        "Total LLM API calls",
        ["model"],
    )
    api_cost_usd = Counter(
        "polymarket_hft_api_cost_usd_total",
        "Total estimated LLM API cost in USD",
    )
    kill_switch_activations = Counter(
        "polymarket_hft_kill_switch_total",
        "Number of kill switch activations",
    )

    # ── Gauges ────────────────────────────────────────────────────────────────
    bankroll_usd = Gauge(
        "polymarket_hft_bankroll_usd",
        "Current bankroll in USD",
    )
    daily_pnl_usd = Gauge(
        "polymarket_hft_daily_pnl_usd",
        "Unrealized + realized P&L today",
    )
    open_positions = Gauge(
        "polymarket_hft_open_positions",
        "Number of currently open positions",
    )
    total_exposure_usd = Gauge(
        "polymarket_hft_total_exposure_usd",
        "Total market exposure in USD",
    )
    worker_heartbeat = Gauge(
        "polymarket_hft_worker_last_heartbeat",
        "Timestamp of last worker heartbeat",
        ["worker"],
    )
    brier_score_7d = Gauge(
        "polymarket_hft_brier_score_7d",
        "Rolling 7-day Brier score",
    )

    # ── Histograms ────────────────────────────────────────────────────────────
    signal_latency_ms = Histogram(
        "polymarket_hft_signal_latency_ms",
        "Time from news arrival to signal emission (ms)",
        buckets=[50, 100, 200, 500, 1000, 2000, 5000],
    )
    order_latency_ms = Histogram(
        "polymarket_hft_order_latency_ms",
        "Time from signal to order submission (ms)",
        buckets=[10, 25, 50, 100, 250, 500, 1000],
    )


def start_metrics_server() -> None:
    if not _PROMETHEUS_AVAILABLE:
        log.warning("prometheus_client not installed — metrics server disabled")
        return
    start_http_server(cfg.prometheus_port)
    log.info("Prometheus metrics server started on :%d", cfg.prometheus_port)


async def update_portfolio_metrics() -> None:
    """Refresh portfolio gauges from Redis state. Called every 30s."""
    if not _PROMETHEUS_AVAILABLE:
        return
    try:
        from persist import redis_state
        from portfolio.positions import get_portfolio_summary
        from persist.db import get_daily_pnl, get_brier_score

        bl = await redis_state.get_bankroll()
        if bl:
            bankroll_usd.set(bl)

        summary = await get_portfolio_summary()
        open_positions.set(summary["open_positions"])
        total_exposure_usd.set(summary["total_exposure_usd"])

        pnl = await get_daily_pnl()
        if pnl is not None:
            daily_pnl_usd.set(pnl)

        bs = await get_brier_score(lookback_days=7)
        if bs is not None:
            brier_score_7d.set(bs)

    except Exception as exc:
        log.debug("metrics update error: %s", exc)
